sudo: required
services:
  - docker
before_install:
  - docker build -t jeremyhxx/docker-complex-test -f ./client/Dockerfile.dev ./client
script:
  - docker run jeremyhxx/docker-complex-test npm run test -- --coverage
after_success:
  - docker build -t jeremyhxx/docker-complex-client ./client
  - docker build -t jeremyhxx/docker-complex-nginx ./nginx
  - docker build -t jeremyhxx/docker-complex-server ./server
  - docker build -t jeremyhxx/docker-complex-worker ./worker
# Login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push to docker hub
  - docker push jeremyhxx/docker-complex-client
  - docker push jeremyhxx/docker-complex-nginx 
  - docker push jeremyhxx/docker-complex-server
  - docker push jeremyhxx/docker-complex-worker 
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-complex"
  env: "DockerComplex-env"
  bucket_name: "elasticbeanstalk-us-east-1-825179159969"
  bucket_path: "docker-complex"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_ID"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"